# Support the author by using the funding links below
# Developed and maintained by dev_harry
#Github sponsors: https://github.com/sponsors/Happybajwa
# Buy Me a Coffee https://www.buymeacoffee.com/KmeqZ6xKg3

custom: ['https://github.com/sponsors/Happybajwa', 'https://www.buymeacoffee.com/KmeqZ6xKg3']

# Support this project
# Your contributions help maintain and improve this free, open-source tool
# Thank you for considering supporting the development! ❤️
